spring.application.name=publicapi

spring.output.ansi.enabled=always

logging.level.root=info

# OpenAPI 관련 서버 정보
# 개발자가 추가 생성한 설정정보
redtable.service-key=E9srtWfHUmhcZy2u2CXdXqbHk3LqckUwBmgiO2xl7pjCTgE00a3YwdrwWCN4ZVTk
redtable.base-url=https://busan-food.openapi.redtable.global