/*
 * This source file was generated by the Gradle 'init' task
 */
package ex03_syntax;

public class App {

    public static void main(String[] args) {
        System.out.println("Java 문법 2");

        boolean have_Money = true;

        if (have_Money) {
            System.out.println("택시를 탄다");
        } else {
            System.out.println("걸어간다.");
        }

        int money = 9000;

        if (money > 15000) {
            System.out.println("집에까지 가주세요~");
        } else if (money > 6000) {
            System.out.println("중간에 내려주세요~");
        } else {
            System.out.println("걸어갈께요. ㅠㅠ");
        }

        int month = 4;
        String monStr = "";

        // 
        switch (month) {
            case 1:
                monStr = "1월";
                break;

            case 2:
                monStr = "2월";
                break;

            case 3:
                monStr = "3월";
                break;

            case 4:
                monStr = "4월";
                break;

            default:
                monStr = "알아서 하세요~";
                break;
        }

        System.out.println("지금은 " + monStr + " 입니다");

        // while 문
        int hit = 0;

        while (hit < 10) {
            hit++;
            System.out.println("나무를 " + hit + "번 찍습니다.");

            if (hit == 10) {
                System.out.println("나무가 넘어갑니다.");
            }
        }

        // for 문
        String[] numbers = {"One", "Two", "Four"};
        for (int i=0; i < numbers.length; i++) {
            System.out.println(numbers[i]);
        }

        // foreach 문
        for (String number: numbers) {
            System.out.println(number);
        }
    }
}
