CREATE TABLE FOOD (
    ID          NUMBER PRIMARY KEY,
    NAME        VARCHAR2(200) NOT NULL,
    CATEGORY    VARCHAR2(50) NOT NULL,
    RATING      NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
    MEMO        VARCHAR2(1000),
    EAT_DATE    DATE NOT NULL,
    CREATED_AT  DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE FOOD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

<<<<<<< HEAD
--SELECT table_name FROM user_tables WHERE table_name = 'FOOD';

SELECT * FROM FOOD;
=======
COMMIT;

SELECT table_name FROM user_tables WHERE table_name = 'FOOD';
>>>>>>> ef3e18d594b405c89cc43c9924afb3e789798e76
