spring.application.name=foodsite

spring.output.ansi.enabled=always
# 로그레벨 설정
logging.level.root=info
logging.level.com.pknu26.foodsite.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=foodsite
spring.datasource.password=foodsite1234

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pknu26.foodsite.dto
mybatis.configuration.map-underscore-to-camel-case=true

spring.thymeleaf.cache=false